-- translation notice : don't change the keys of tables or it won't work anymore (the text within the [ ]), the color coding part mustn't be changed either (|cff00ffff and |r).

-------------------------------
-- table for chat report settings, no problem changing the text lenght as it's outputted to chat frame
CombuLocEN = {["lockon"] = "|cff00ffffCombustionHelper locked|r",
			["lockoff"] = "|cff00ffffCombustionHelper unlocked|r",
			["reporton"] = "|cff00ffffCombustionHelper status report enabled|r",
			["ffbon"] = "|cff00ffffFrostFire Bolt mode enabled|r",
			["ffboff"] = "|cff00ffffFrostFire Bolt mode disabled|r",
			["dmgreporton"] = "|cff00ffffDamage report mode enabled|r",
			["dmgreportoff"] = "|cff00ffffDamage report mode disabled|r",
			["doton"] = "|cff00ffffCombustion dot tracker enabled|r",
			["dotoff"] = "|cff00ffffCombustion dot tracker disabled|r",	
			["lbon"] = "|cff00ffffEarly Bomb refresh mode enabled|r",
			["lboff"] = "|cff00ffffEarly Bomb refresh mode disabled|r",
			["pyroon"] = "|cff00ffffPyroblast report mode enabled|r",
			["pyrooff"] = "|cff00ffffPyroblast report mode disabled|r",
			["impacton"] = "|cff00ffffImpact mode enabled|r",
			["impactoff"] = "|cff00ffffImpact mode disabled|r",
			["baron"] = "|cff00ffffBar timer mode enabled|r",
			["baroff"] = "|cff00ffffBar timer mode disabled|r",
			["criton"] = "|cff00ffffCritical Mass tracker enabled|r",
			["critoff"] = "|cff00ffffCritical Mass tracker disabled|r",
			["ignpredon"] = "|cff00ffffBeta ignite predicter enabled|r",
			["ignpredoff"] = "|cff00ffffBeta ignite predicter disabled|r",
			["fson"] = "|cff00ffffFlamestrike tracker enabled|r",
			["fsoff"] = "|cff00ffffFlamestrike tracker disabled|r",
			["munchon"] = "|cff00ffffIgnite munching report enabled|r",
			["munchoff"] = "|cff00ffffIgnite munching report disabled|r",
			["lbtrackon"] = "|cff00ffffBomb tracker enabled|r",
			["lbtrackoff"] = "|cff00ffffBomb tracker disabled|r",
			["reset"] = "|cff00ffffCombustionHelper Savedvariables have been resetted, you can logout now.|r",
			["ffbglyphon"] = "|cff00ffffFrostfire Bolt glyph detected, FFB mode enabled|r",
			["ffbglyphoff"] = "|cff00ffff No Frostfire Bolt glyph detected, FFB mode disabled|r",
			["autohidemess"] = "|cff00ffffCombustion Helper back in %d seconds|r",
			["startup"] = "|cff00ffffCombustion Helper is loaded. Interface Panel -> Addons for Config.|r",
			["combuon"] = "|cff00ffffNo Combustion spell in Spellbook, CombustionHelper hiding now.|r",
			["combuoff"] = "|cff00ffffCombustion spell in Spellbook, CombustionHelper back in.|r",
			["lbrefresh"] = "|cffff0000 -- You refreshed your Bomb on |cffffffff%s |cffff0000too early. --|r",
			["lbmiss"] = "|cffff00ff -- Bomb cast on |cffffffff%s |cffff00ffmissed !! --",
			["pyrorefresh"] = "|cffff0000 -- You just wasted a Hot Streak, it got refreshed before getting used. --|r",
            ["ignrep"] = "|cffff0000 -- Ignite expected : |cffffffff%d |cffff0000- applied : |cffffffff%d |cffff0000- lost : |cffffffff%s |cffff0000--|r",
			["lbreport"] = "|cffff0000 -- Earlier Bomb refresh for this fight : |cffffffff%d |cffff0000--|r",
			["pyroreport"] = "|cffff0000 -- Hot Streak refresh for this fight : |cffffffff%d |cffff0000--|r",
			["slashcomm"] = "|cff00ffffOpening Combustion Helper config panel|r",
			["comburepthres"] = "|cff00ffffCombustionHelper report threshold set to : %.0f dot damage.|r",
			["ignadjvalue"] = "|cff00ffffCombustionHelper Ignite adjust set to : %.1f secs.|r",
			["redzonetimer"] = "|cff00ffffCombustionHelper red zone for timers set to : %.1f secs.|r",
			["interfaceGraph"] = "Graphical options",
			["combureport1"] = "|cffff0000 -- Total Combustion : |cffffffff%d |cffff0000- Ticks : |cffffffff%d |cffff0000- Dmg : |cffffffff%d |cffff0000- Targets : |cffffffff%d |cffff0000--|r",
			["combureport2"] = "|cffff0000 -- Prev. Combustion : |cffffffff%d |cffff0000- Ticks : |cffffffff%d |cffff0000- Dmg : |cffffffff%d |cffff0000- Targets : |cffffffff%d |cffff0000--|r",
			["pyroenableon"] = "|cff00ffffPyroblast tracker enabled|r",
			["pyroenableoff"] = "|cff00ffffPyroblast tracker disabled|r",
			["lbenableon"] = "|cff00ffffBomb tracker enabled|r",
			["lbenableoff"] = "|cff00ffffBomb tracker disabled|r",
			}
			
-------------------------------
-- table for option mouseover info, no problem changing text lenght here too, tooltip size change according to lenght
combuoptioninfotableEN = {
	["CombuScaleSlider"] = "Use this slider to adjust the size of CombustionHelper. Note that you'll have to replace it at its position afterwards.",
	["CombulockButton"] = "Lock the frame when checked, unlock the frame when unchecked.",
	["CombucritButton"] = "Enable the tracker for Spell Critical Strike debuff provided by firemages and warlocks on your target.",
	["ComburefreshButton"] = "Enable the warning mode in chat frame when you refresh a Bomb too early or when you miss your Bomb spell on your target (also enable the 'fizzle' sound).",
	["CombureportButton"] = "Add value report of damage ticks for each spells monitored by CombustionHelper. There is a small delay because info will available only after the first tick happened.",
	["Combureportthreshold"] = "Enable then set a value in the editbox to have the background color changing for Combustion and Impact only when the value of Ignite on your target will be higher than set value.",
	["Combureportvalue"] = "Enable then set a value in the editbox to have the background color changing for Combustion and Impact only when the value of Ignite on your target will be higher than set value.",
	["CombuIgnitePredictButton"] = "Enable the beta predicter for Ignite damage report. This allow to have instant info instead of waiting for the tick to happen. Value added using this mode will have a * before the text, so you know that this is maybe non accurate info. If the predicted value is right then the text will turn green when the tick will happen and red when not.",
	["CombuIgniteAdjustbutton"] = "The beta predicter monitors crits happening within a set timeframe to know how the damage will behave. The latency (lag) can change the accuracy of it. First test on a dummy with scorch spam, if you see lot of red text, change this value in increment of 0,1 secs until you see more green text.", 
	["CombuIgniteAdjustvalue"] = "The beta predicter monitors crits happening within a set timeframe to know how the damage will behave. The latency (lag) can change the accuracy of it. First test on a dummy with scorch spam, if you see lot of red text, change this value in increment of 0,1 secs until you see more green text.",
	["CombuffbButton"] = "Enable or disable FrostFire dot tracking, regardless of the presence of FFB glyph.",
	["CombuTimerbutton"] = "Enter a value in seconds to adjust the red zone of all the timer bars of the addon.",
	["CombuTimervalue"] = "Enter a value in seconds to adjust the red zone of all the timer bars of the addon.",
	["ComburefreshpyroButton"] = "Enable the warning in chat frame when you forget to use your Hot Streak proc and also enable the report at the end of the fight.",
	["CombuimpactButton"] = "Enable tracking of Impact procs and background color changing in when combustion is on cooldown.",
	["CombutrackerButton"] = "Add a timer bar in Combustion status frame to show the current duration of applied Combustion on your target and the cooldown. Also add information report in chat frame.",
	["CombuchatButton"] = "Enable or disable outputs in chat frame for settings changes and autohide information.",
	["CombuLBtrackerButton"] = "Enable or disable the multi target Bomb tracker. This add a small panel with information on all your Bomb spells.",
	["CombuLBtargetButton"] = "When disabled, this settings hide the multi target Bomb tracker when you only have a Bomb active and it's on your target.",
	["LBtrackerPosition"] = "Use the Dropdown menu to set the position of the multi target Bomb tracker around CombustionHelper main frame.",
	["LBtrackerDropDown"] = "Use the Dropdown menu to set the position of the multi target Bomb tracker around CombustionHelper main frame.",
	["CombuAutohideInfo"] = "Use the Dropdown menu to choose the Autohide mode of CombustionHelper. No Autohide : keep frame visible at all times. Autohide only out of combat : only show panel in combat whether Combustion is up or not. Autohide OOC and Combustion off cd : only show when Combustion is up and in combat.",
	["CombuAutohideDropDown"] = "Use the Dropdown menu to choose the Autohide mode of CombustionHelper. No Autohide : keep frame visible at all times. Autohide only out of combat : only show panel in combat whether Combustion is up or not. Autohide OOC and Combustion off cd : only show when Combustion is up and in combat.",
	["CombuBarButton"] = "Enable or disable timer bars for Bomb, Ignite, Pyroblast dot and FrostFire dot.",
	["CombuBarSlider"] = "Use this slider to adjust the width of the timer bars for Bomb, Ignite, Pyroblast dot and FrostFire dot. This will also change the width of the main frame.",
	["Combubarcolornormal"] = "Clicking on this color swatch will open the color picker to change the colors of all the timer bars of CombustionHelper when timer is more than the warning value.",
	["Combubarcolorwarning"] = "Clicking on this color swatch will open the color picker to change the colors of all the timer bars of CombustionHelper when timers is less than the warning value.",
	["CombubeforefadeSlider"] = "This slider will change the time in seconds before the frame will start to autohide after Combustion have been used. Default is 15 seconds.",
	["CombufadeoutspeedSlider"] = "This slider will change the time in seconds of the speed to hide the panel when autohiding. Default is 2 seconds.",
	["CombufadedtimeText"] = "This value show the time in seconds the panel will spend being hidden between Combustion uses. You cannot change this value directly since it's related to the other settings around.",
	["CombufadedtimeFrame"] = "This value show the time in seconds the panel will spend being hidden between Combustion uses. You cannot change this value directly since it's related to the other settings around.",
	["CombufadeinspeedSlider"] = "This slider will change the time in seconds of the speed to show the panel when coming out of hiding. Default is 2 seconds.",
	["CombuafterfadeSlider"] = "This slider will change the time in seconds when the frame come out of hiding before Combustion become available. Default is 15 seconds.",
	["ComburesetButton"] = "Use this button when you messed up with the settings and want to go back to clean state. After having used it, best practice is to logout and login for everything to be resetted.",
	["CombuFlamestrikeButton"] = "Enable or disable the Flamestrike tracker. It will track separately the regular Flamestrike and the Flamestrike procced by using Blastwave with Improved Flamestrike since both dot stacks. Only the last cast of each type will be tracked to avoid unnecessary timers.",
	["CombuMunchingButton"] = "Enable or disable the Ignite munching report. It'll record each fire spell criticals and every Ignite application. At the end of the fight it'll report to you these numbers so you know how much damage you have lost due to munching and early dying of your targets. This information, though not being critical, will allow you to know your supposed damage. IMPORTANT NOTICE : due to impact and dot spreading, only criticals done to your current target will be taken in account !! Also this feature rely on the ignite predicter mechanics, so it need to be enabled for it to work.",
	["Combubgcolorcombustion"] = "Set the color for the background and border when Combustion is available and all 3 dots are up or if thresold is enabled and crossed.",
	["Combubgcolorimpact"] = "Set the color for the background and border when Impact is available.",
	["Combubgcolornormal"] = "Set the color for the background of the frame outside Combustion and Impact times. Default color may be too darker if you choose another background.",
	["CombuTextureDropDown"] = "Use the Dropdown menu to choose the texture for timers bars.",
	["CombuTextureInfo"] = "Use the Dropdown menu to choose the texture for timers bars.",
	["CombuFontDropDown"] = "Use the Dropdown menu to choose the font for all the texts.",
	["CombuFontInfo"] = "Use the Dropdown menu to choose the font for all the texts.",
	["CombuBorderDropDown"] = "Use the Dropdown menu to choose the border for the main frame and Bomb/FS tracker frame.",
	["CombuBorderInfo"] = "Use the Dropdown menu to choose the border for the main frame and Bomb/FS tracker frame.",
	["CombuBackgroundDropDown"] = "Use the Dropdown menu to choose the background for the main frame and Bomb/FS tracker frame.",
	["CombuBackgroundInfo"] = "Use the Dropdown menu to choose the background for the main frame and Bomb/FS tracker frame.",
	["CombuEdgeSizeSlider"] = "Use this slider to choose the size of the borders for the main frame and Bomb/FS tracker frame.",
	["CombuTileSizeSlider"] = "Use this slider to choose the size of the texture tiles used in the background for the main frame and Bomb/FS tracker frame. This slider is used only if the Tiles button is checked.",
	["CombuTileButton"] = "Enable or disable the tiles for the background for the main frame and Bomb/FS tracker frame. When enabled, the chosen background will be repeated according to the size chosen in the tile size slider.",
	["CombuInsetsSlider"] = "Use this slider to define how far from the border the background should start appearing.",
	["CombuSoundInfo"] = "Use the Dropdown menu to choose the audio warning when threshold is crossed.",
	["CombuSoundDropDown"] = "Use the Dropdown menu to choose the audio warning when threshold is crossed.",
    ["CombuThresholdSoundButton"] = "Enable the audio warning when Ignite threshold is crossed.",
	["Combuedgecolornormal"] = "Set the color for the border of the frame outside Combustion and Impact times.",
    ["CombuTickPredictButton"] = "Replace the Ignite damage value in the Status zone by the estimated damage for each tick of Combustion and the number of ticks depending from your current haste.",
	["CombuPyroEnableButton"] = "Enable or disable Pyroblast tracking in the main window.",
	["CombuLBEnableButton"] = "Enable or disable Bomb tracking in the main window.",
	}

-------------------------------
-- table for option panel localisation, try to stick to the lenght as it could overflow if bigger
CombuOptLocEN = {
	["CombuScaleSlider"] = "Size",
	["CombulockButton"] = "Lock CombustionHelper",
	["CombucritButton"] = "Critical Mass tracker",
	["ComburefreshButton"] = "Early/Missed Bomb warning",
	["CombureportButton"] = "Damage report Mode",
	["Combureportthreshold"] = "Threshold :",
	["CombuIgnitePredictButton"] = "Ignite Predicter (beta)",
	["CombuIgniteAdjustbutton"] = "Adjust ignite timing :", 
	["CombuffbButton"] = "FFB mode enabled",
	["CombuTimerbutton"] = "Timer red zone :",
	["ComburefreshpyroButton"] = "Pyroblast/Hot Streak report",
	["CombuimpactButton"] = "Enable Impact mode",
	["CombutrackerButton"] = "Enable Combustion Tracker",
	["CombuchatButton"] = "Config messages in chat",
	["CombuLBtrackerButton"] = "Enable Bomb Tracker",
	["CombuLBtargetButton"] = "Always show Bomb on target",
	["CombuAutohideInfo"] = "AutoHide mode :",
	["CombuBarButton"] = "Enable Bar timer mode",
	["CombuBarSlider"] = "Bar Width",
	["CombuTextureInfo"] = "Bar Texture :",
	["CombuFontInfo"] = "Text Font :",
	["CombuBorderInfo"] = "Frame border :",
	["CombuBackgroundInfo"] = "Background :",
	["CombuEdgeSizeSlider"] = "Edge Size",
	["CombuSliderInfo"] = "Below you can adjust the timers for Fade in, Fade out and for autohide in combat.",
	["CombubeforefadeSlider"] = "Timer pre fade",
	["CombufadeoutspeedSlider"] = "Fadeout",
	["CombufadedtimeText"] = "Faded time",
	["CombufadeinspeedSlider"] = "Fadein",
	["CombuafterfadeSlider"] = "Time post fade",
	["ComburesetButton"] = "Reset SavedVariables",
	["CombuFlamestrikeButton"] = "Enable Flamestrike tracker",
	["CombuTileSizeSlider"] = "Tile Size",
	["CombuTileButton"] = "Tile background",
	["CombuInsetsSlider"] = "Bg Insets",
	["Combubarcolornormal"] = "Bar color (normal)",
	["Combubarcolorwarning"] = "Bar color (warning)",
	["Combubgcolornormal"] = "Background color (normal)",
	["Combubgcolorimpact"] = "Background color (Heated Up)",
	["Combubgcolorcombustion"] = "Background color (Combustion up)",
	["CombuMunchingButton"] = "Ignite munching report",
	["CombuLanguageInfo"] = "Language :",
    ["CombuSoundInfo"] = "Threshold warning :",
    ["CombuThresholdSoundButton"] = "Audio warning for threshold",
	["Combuedgecolornormal"] = "Border color (normal)",
    ["CombuTickPredictButton"] = "Combustion Tick damage/nbr prediction",
    ["CombuPyromaniacButton"] = "Missing Pyromaniac warning",
	["Combubgcolorwarning"] = "Background color (Warning)",
	["CombuHotStreakButton"] = "Heating Up warning",
	["CombuPyroEnableButton"] = "Enable Pyroblast tracking",
	["CombuLBEnableButton"] = "Enable Bomb tracking",
	}


-------------------------------
-- table for Autohide dropdown
CombuAutohideListEN = {
   "No Autohide",
   "Autohide only out of Combat",
   "Autohide OOC and Combustion off cd",
}

-------------------------------
-- table for text within frame, try to stick to the lenght as it could overflow if bigger
CombuLabelEN = {["autohide"] = "Autohiding now.",
				["ignwhite0"] = "|cffffffff*%.0f Dmg|r",
				["dmggreen0"] = "|cff00ff00%.0f Dmg|r",
				["dmgred0"] = "|cffff0000%.0f Dmg|r",
				["dmgwhite0"] = "|cffffffff%.0f Dmg|r",
				["ignite"] = "|cffffffffIgnite|r",
				["ignshort"] = "|cffff0000Ign|r",
				["flamestrike"] = "Flamestrike",
				["blastwave"] = "Blastwave FS",
				["lbshort"] = "|cffff0000Bomb|r",
				["ffbglyph"] = "|cffff0000Glyph|r",
				["ffbshort"] = "|cffff0000FFB|r",
				["frostfire"] = "FrostFire Bolt",
				["pyroblast"] = "Pyroblast",
				["lb"] = "Bomb",
				["pyroshort"] = "|cffff0000Pyro|r",
				["ignCBgreen"] = "|cff00ff00Ignite : %.0f - CB Up|r",
				["ignCBred"] = "|cffffcc00Ignite : %.0f - CB Up|r",
				["combup"] = "Combustion Up !",
				["impactup"] = "|cff00ff00Impact Up for %.1f !!|r",
				["combmin"] = "Combustion in %d:%0.2d",
				["combsec"] = "Combustion in %.0fsec",
				["critmasswhite"] = "|cffffffff Critical Mass|r",
				["critmassred"] = "|cffff0000No Critical Mass !!|r",
				}