-- translation notice : don't change the keys of tables or it won't work anymore (the text within the [ ]), the color coding part mustn't be changed either (|cff00ffff and |r).

--if GetLocale() == "deDE" then

-------------------------------
-- table for chat report settings, no problem changing the text lenght as it's outputted to chat frame
CombuLocDE = {["lockon"] = "|cff00ffffCombustionHelper gesperrt|r",
["lockoff"] = "|cff00ffffCombustionHelper entsperrt|r",
["reporton"] = "|cff00ffffCombustionHelper Status-Bericht ein|r",
["ffbon"] = "|cff00ffffFrostfeuerblitz-Modus ein|r",
["ffboff"] = "|cff00ffffFrostfeuerblitz-Modus aus|r",
["dmgreporton"] = "|cff00ffffSchadensbericht ein|r",
["dmgreportoff"] = "|cff00ffffSchadensbericht aus|r",
["doton"] = "|cff00ffffZeige Entzünden-DoT|r",
["dotoff"] = "|cff00ffffVerstecke Entzünden-DoT|r",	
["lbon"] = "|cff00ffffZeige Hinweis für zu früh gewirkte Lebende Bombe|r",
["lboff"] = "|cff00ffffVerstecke Hinweis für zu früh gewirkte Lebende Bombe|r",
["pyroon"] = "|cff00ffffPyroschlag-Bericht ein|r",
["pyrooff"] = "|cff00ffffPyroschlag-Bericht eaus|r",
["impacton"] = "|cff00ffffEinschlag-Modus ein|r",
["impactoff"] = "|cff00ffffEinschlag-Modus aus|r",
["baron"] = "|cff00ffffBalken-Zähler ein|r",
["baroff"] = "|cff00ffffBalken-Zähler aus|r",
["criton"] = "|cff00ffffZeige Kritische Masse|r",
["critoff"] = "|cff00ffffVerstecke Kritische Masse|r",
["ignpredon"] = "|cff00ffffBeta Entzünden-Voraussage ein|r",
["ignpredoff"] = "|cff00ffffBeta Entzünden-Voraussage aus|r",
["fson"] = "|cff00ffffZeige Flammenstoß-Dauer|r",
["fsoff"] = "|cff00ffffVerstecke Flammenstoß-Dauer|r",
["munchon"] = "|cff00ffffZeige Ignite-Munching Bericht|r",
["munchoff"] = "|cff00ffffVerstecke Ignite-Munching Bericht|r",
["lbtrackon"] = "|cff00ffffZeige Lebende Bombe auf allen Zielen|r",
["lbtrackoff"] = "|cff00ffffVerstecke Lebende Bombe auf allen Zielen|r",
["reset"] = "|cff00ffffCombustionHelper Savedvariables wurde zurückgesetzt, du kannst dich nun ausloggen.|r",
["ffbglyphon"] = "|cff00ffffFrostfeuerblitz-Glyphe gefunden, FFB-Modus ein|r",
["ffbglyphoff"] = "|cff00ffffKeine Frostfeuerblitz-Glyphe gefunden, FFB-Modus aus|r",
["autohidemess"] = "|cff00ffffCombustionHelper wieder da in %d Sekunden|r",
["startup"] = "|cff00ffffCombustionHelper wurde geladen. Interface Fenster -> Addons zum Einstellen.|r",
["combuon"] = "|cff00ffffKein Einäschern-Zauber im Zauberbuch, verstecke CombustionHelper.|r",
["combuoff"] = "|cff00ffffEinäschern-Zauber im Zauberbuch gefunden, zeige CombustionHelper.|r",
["lbrefresh"] = "|cffff0000 -- Du hast deine Lebende Bombe auf |cffffffff%s |cffff0000zu früh erneuert. --|r",
["lbmiss"] = "|cffff00ff -- Lebende Bombe auf |cffffffff%s |cffff00ffhat verfehlt !! --",
["pyrorefresh"] = "|cffff0000 -- Du hast gerade Kampfeshitze verschwendet, sie wurde durch eine neuere überschrieben. --|r",
["ignrep"] = "|cffff0000 -- Entzünden erwartet : |cffffffff%d |cffff0000- tatsächliches : |cffffffff%d |cffff0000- verloren : |cffffffff%s |cffff0000--|r",
["lbreport"] = "|cffff0000 -- Zu früh gewirkte Lebende Bomben in diesem Kampf : |cffffffff%d |cffff0000--|r",
["pyroreport"] = "|cffff0000 -- Kampfeshitze gewirkte in diesem Kampf : |cffffffff%d |cffff0000--|r",
["slashcomm"] = "|cff00ffffÖffne CombustionHelper Einstellungs-Menü|r",
["comburepthres"] = "|cff00ffffCombustionHelper report threshold set to : %.0f dot damage.|r",
["ignadjvalue"] = "|cff00ffffCombustionHelper Ignite adjust set to : %.1f secs.|r",
["redzonetimer"] = "|cff00ffffCombustionHelper rote zone timers : %.1f secs.|r",
["interfaceGraph"] = "Grafiken options",
["combureport1"] = "|cffff0000 -- Total Einäschern : |cffffffff%d |cffff0000- Ticks : |cffffffff%d |cffff0000- Dmg : |cffffffff%d |cffff0000- Ziels : |cffffffff%d |cffff0000--|r",
["combureport2"] = "|cffff0000 -- Vor. Einäschern : |cffffffff%d |cffff0000- Ticks : |cffffffff%d |cffff0000- Dmg : |cffffffff%d |cffff0000- Ziels : |cffffffff%d |cffff0000--|r",
["pyroenableon"] = "| cff00ffffPyroblast tracker enabled | r",
["pyroenableoff"] = "| cff00ffffPyroblast tracker deaktiviert | r",
["lbenableon"] = "| cff00ffffBomb tracker enabled | r",
["lbenableoff"] = "| cff00ffffBomb tracker deaktiviert | r",
}

-------------------------------
-- table for option mouseover info, no problem changing text lenght here too, tooltip size change according to lenght
combuoptioninfotableDE = {
["CombuScaleSlider"] = "Stellt die Größe von CombustionHelper ein. Anschliessend wirst du die Position des Fensters erneut anpassen müssen.",
["CombulockButton"] = "Sperrt/Entsperrt das Fenster.",
["CombucritButton"] = "Aktivieren um den Kritische Treffer-Debuff von Hexenmeistern/Feuermagiern auf deinem Ziel zu verfolgen.",
["ComburefreshButton"] = "Gibt eine Warnung im Chat aus, falls Lebende Bombe zu früh erneuert wurde oder verfehlte (aktiviert auch den 'fizzle' Sound).",
["CombureportButton"] = "Fügt eine Anzeige hinzu, die den zusammengefassten Schadenswert all deiner Dots darstellt. Die Anzeige erscheint etwas verzögert, da für die Berechnung die DoTs mindestens einmal getickt haben müssen.",
["Combureportthreshold"] = "Aktivieren, damit sich CombustionHelper grün verfärbt, wenn der zusammengefasste Schadenswert aller DoTs den angegebenen Schwellenwert übersteigt. Zusätzlich färbt sich der Rand gelb, wenn Einschlag aktiv ist.",
["Combureportvalue"] = "Aktivieren, damit sich CombustionHelper grün verfärbt, wenn der zusammengefasste Schadenswert aller DoTs den angegebenen Schwellenwert übersteigt. Zusätzlich färbt sich der Rand gelb, wenn Einschlag aktiv ist.",
["CombuIgnitePredictButton"] = "Aktivieren um eine Beta-Version der Entzünden-Voraussage hinzuzuschalten. Dies gibt sofort einen geschätzten Entzünden-Wert aus, bevor Entzünden überhaupt getickt hat. Der geschätzte Wert hat ein * davor, um es vom tatsächlichen Wert zu unterscheiden. Wenn der geschätzte Wert korrekt war, verfärbt sich der Text grün. Falls nicht, wird er rot",
["CombuIgniteAdjustbutton"] = "Die Beta-Voraussage verfolgt kritische Treffer innerhalb eines vorgegebenen Zeitfensters, um das mögliche Verhalten abzuschätzen. Die Verzögerung (Lag) kann die Genauigkeit beeinflussen. Teste an einer Trainingspuppe mit Versengen, ob sich der geschätzte Entzünden-Schaden öfter rot oder grün verfärbt. Erhöhe den Wert in 0,1 Schritten, bis du mehr grünen als roten Text siehst.", 
["CombuIgniteAdjustvalue"] = "Die Beta-Voraussage verfolgt kritische Treffer innerhalb eines vorgegebenen Zeitfensters, um das mögliche Verhalten abzuschätzen. Die Verzögerung (Lag) kann die Genauigkeit beeinflussen. Teste an einer Trainingspuppe mit Versengen, ob sich der geschätzte Entzünden-Schaden öfter rot oder grün verfärbt. Erhöhe den Wert in 0,1 Schritten, bis du mehr grünen als roten Text siehst.",
["CombuffbButton"] = "Aktivieren um den Frostfeuerblitz-DoT zu verfolgen, unabhängig davon, ob die FFB-Glyphe aktiv ist oder nicht.",
["CombuTimerbutton"] = "Gib einen Wert in Sekunden ein, ab dem sich die Balken rot verfärben sollen, wenn die verbleibende Dauer unter den angegebenen Wert fällt.",
["CombuTimervalue"] = "Gib einen Wert in Sekunden ein, ab dem sich die Balken rot verfärben sollen, wenn die verbleibende Dauer unter den angegebenen Wert fällt.",
["ComburefreshpyroButton"] = "Gibt einen Warn-Hinweis im Chat aus, falls du vergisst einen Kampfeshitze-Proc zu benutzen. Zudem wird am Ende des Kampfes ein Bericht über all deine Kampfeshitz-Procs des gesamten Kampfverlaufes ausgegeben.",
["CombuimpactButton"] = "Aktiviert die Verfolgung von Einschlag-Proccs und den Hintergrundfarbwechsel, wenn Einäschern Abklingzeit hat.",
["CombutrackerButton"] = "Fügt einen Balken hinzu, der die verbleibende Dauer eines aktiven Einäschern-Zaubers auf deinem Ziel anzeigt und der cooldown. Fügen Sie außerdem Informationen Bericht in Chatfenster.",
["CombuchatButton"] = "Falls aktiviert, werden im Chat Hinweise über Einstellungs-Änderungen und, ob Combustionhelper versteckt ist oder angezeigt wird, ausgegeben.",
["CombuLBtrackerButton"] = "Aktivieren um Lebende Bombe auf mehreren Zielen zu verfolgen. Dies fügt ein kleines Fenster hinzu, mit Infos über all deine aktiven Lebenden Bomben.",
["CombuLBtargetButton"] = "Wenn deaktiviert versteckt diese Einstellung den Tracker für mehrere Lebende Bomben, wenn du nur eine Lebende Bombe auf deinem Ziel aktiv hast.",
["LBtrackerPosition"] = "Verwende das Aufklapp-Menü um die Position der Mehrziel-Anzeige um CombustionHelpers Hauptfenster herum festzulegen.",
["LBtrackerDropDown"] = "Verwende das Aufklapp-Menü um die Position der Mehrziel-Anzeige um CombustionHelpers Hauptfenster herum festzulegen.",
["CombuAutohideInfo"] = "Verwende das Aufklapp-Menü, um die Autohide (automatisches Verstecken) Funktion von CombustionHelper auszuwählen. Kein Autohide : Das Fenster wird zu jeder Zeit angezeigt. Autohide ausserhalb vom Kampf : Das Fenster wird nur im Kampf angezeigt, unabhängig davon, ob Einäschern noch Abklingzeit hat oder nicht. Autohide OOC und Einäschern off cd : Zeigt das Fenster nur im Kampf an und auch nur wenn Einäschern bereit ist.",
["CombuBarButton"] = "Aktiviere oder Deaktiviere Timer-Balken für Lebende Bombe, Entzünden, Pyroschlag-DoT und Frostfeuerblitz-DoT.",
["CombuBarSlider"] = "Verwende diesen Schieberegler, um die Breite der Timer-Balken für Lebende Bombe, Entzünden, Pyroschlag-DoT und Frostfeuerblitz-DoT anzupassen. Dies ändert ebenfalls die Breite des Hauptfensters.",
["Combubarcolornormal"] = "Das Klicken auf das Farbmuster wird die Farbauswahl öffnen, um die Farben aller Timer-Balken von CombustionHelper zu ändern, wenn diese über dem Warnungswert liegen.",
["Combubarcolorwarning"] = "Das Klicken auf das Farbmuster wird die Farbauswahl öffnen, um die Farben aller Timer-Balken von CombustionHelper zu ändern, wenn diese unter dem Warnungswert liegen.",
["CombubeforefadeSlider"] = "Dieser Schieberegler ändert die Zeit in Sekunden bevor das Fenster automatisch versteckt wird nachdem Einäschern benutzt wurde. Defaulwert ist 15 Sekunden.",
["CombufadeoutspeedSlider"] = "Dieser Schieberegler ändert die Zeit in Sekunden bis das Fenster automatisch versteckt wird. Defaultwert ist 2 Sekunden.",
["CombufadedtimeText"] = "Dieser Wert zeigt die Zeit in Sekunden bis das Fenster zwischen zwei Nutzungen von Einäschern versteckt wird. Du kannst diesen Wert nicht ändern, da er von anderen Einstellungen abhängt.",
["CombufadedtimeFrame"] = "Dieser Wert zeigt die Zeit in Sekunden bis das Fenster zwischen zwei Nutzungen von Einäschern versteckt wird. Du kannst diesen Wert nicht ändern, da er von anderen Einstellungen abhängt.",
["CombufadeinspeedSlider"] = "Dieser Schieberegler verändert die Zeit in Sekunden der Geschwindigkeit bevor das Fenster nicht mehr versteckt wird. Defaultwert sind 2 Sekunden.",
["CombuafterfadeSlider"] = "Dieser Schieberegler verändert die Zeit in Sekunden bevor das Fenster nicht mehr versteckt wird und bevor Einäschern verfügbar ist. Defaultwert is 15 Sekunden.",
["ComburesetButton"] = "Verwende diesen Button, wenn du die Einstellungen vermasselt hast und du zu einem sauberen Zustand zurück willst. Nach der Nutzung logge dich am besten aus und wieder ein, damit alles zurückgesetzt wird.",
["CombuFlamestrikeButton"] = "Aktiviere oder Deaktiviere die Flammenstoß Verfolgung. Diese wird den regulären Flammenstoß und den Flammenstoß, der durch die Nutzung von Druckwelle procct, verfolgen, da beide DoTs sich aufaddieren. Nur der letzte Spruch wird verfolgt, um unnötige Timer zu vermeiden.",
["CombuMunchingButton"] = "Aktiviere oder Deaktiviere den IgniteMmunching Bericht. Dieser wird jeden kritischen Treffer durch Feuerzauber aufnehmen sowie jedes Entzünden. Am Ende des Kampfes wird dies dir die Zahlen ausgeben, damit du weisst, wieviel Schaden du durch Ignite Munching oder zu frühes Sterben deiner Ziele verloren hast. Diese Information, obwohl nicht kritisch, wird dir ermöglichen zu wissen, wieviel Schaden es eigentlich gewesen wäre. WICHTIG : Aufgrund von Einschlag und DoT-Verteilung werden nur kritische Treffer auf deinem aktuellen Ziel betrachtet !! Dieses Feature hängt von der Entzünden-Vorhersage ab, daher muss diese Funktion aktiviert sein.",
["Combubgcolorcombustion"] = "Stellt die Farbe für den Hintergrund und Rand ein, wenn Einäschern verfügbar ist und alle 3 DoTs vorhanden sind oder der Schwellwert aktiviert und überschritten wurde.",
["Combubgcolorimpact"] = "Stellt die Farbe für den Hintergrund und Rand ein, wenn Einschlag verfügbar ist.",
["Combubgcolornormal"] = "Stellt die Farbe für den Hintergrund des Fensters ein, wenn Einäschern und Einschlag nicht verfügbar sind. Die Standardfarbe kann zu dunkel sein, wenn du einen anderen Hintergrund wählst.",
["CombuTextureDropDown"] = "Verwende das Aufklapp-Menü für die Texturen der Timer-Balken.",
["CombuTextureInfo"] = "Verwende das Aufklapp-Menü für die Texturen der Timer-Balken.",
["CombuFontDropDown"] = "Verwende das Aufklapp-Menü, um die Schriftart aller Texte zu wählen.",
["CombuFontInfo"] = "Verwende das Aufklapp-Menü, um die Schriftart aller Texte zu wählen.",
["CombuBorderDropDown"] = "Verwende das Aufklapp-Menü um den Rand des Hauptfensters und des Fensters der LB/FS-Verfolgung auszuwählen.",
["CombuBorderInfo"] = "Verwende das Aufklapp-Menü um den Rand des Hauptfensters und des Fensters der LB/FS-Verfolgung auszuwählen.",
["CombuBackgroundDropDown"] = "Verwende das Aufklapp-Menü um den Hintergrund des Hauptfensters und des Fensters der LB/FS-Verfolgung auszuwählen.",
["CombuBackgroundInfo"] = "Verwende das Aufklapp-Menü um den Hintergrund des Hauptfensters und des Fensters der LB/FS-Verfolgung auszuwählen.",
["CombuEdgeSizeSlider"] = "Verwende diesen Schieberegler um die Größe der Ränder des Hauptfensters und des Fensters der LB/FS-Verfolgung auszuwählen.",
["CombuTileSizeSlider"] = "Verwende diese Schieberegler, um die Größe der Textur-Kacheln, welche für den Hintergrund des Hauptfensters und des Fensters der LB/FS-Verfolgung auszuwählen. Dieser Schiebe-Regler wird nur verwendet, wenn der Kacheln-Button aktiviert wurde.",
["CombuTileButton"] = "Aktiviere oder Deaktiviere die Kacheln fü den Hintergrund des Hauptfensters und des Fensters der LB/FS-Verfolgung. Wenn aktiviert, wird der gewählte Hintergrund wiederholt entsprechend der Größe, die im Kacheln-Größe Schiebe-Regler eingestellt wurde.",
["CombuInsetsSlider"] = "Verwende diesen Schieberegler, um zu definieren, wie weit weg vom Rand entfernt der Hintergrund beginnen soll zu erscheinen.",
["CombuSoundInfo"] = "Verwenden Sie dieses Men�, um die Warnung Sound w�hlen, wenn der Schwellenwert erreicht ist Entz�nden.",
["CombuSoundDropDown"] = "Verwenden Sie dieses Men�, um die Warnung Sound w�hlen, wenn der Schwellenwert erreicht ist Entz�nden.",
["CombuThresholdSoundButton"] = "Aktiviert den Warnton, wenn der Schwellenwert erreicht ist Entz�nden.";
["Combubgcolornormal"] = "Stellt die Farbe für der Ränder des Fensters ein, wenn Einäschern und Einschlag nicht verfügbar sind.",
["CombuTickPredictButton"] = "Replace the Ignite damage value in the Status zone by the estimated damage for each tick of Combustion and the number of ticks depending from your current haste.",
["CombuPyroEnableButton"] = "Aktivieren oder Deaktivieren Pyroblast Tracking im Hauptfenster.",
["CombuLBEnableButton"] = "Aktivieren oder Deaktivieren Bomb Tracking im Hauptfenster.",
}

-------------------------------
-- table for option panel localisation, try to stick to the lenght as it could overflow if bigger
CombuOptLocDE = {
["CombuScaleSlider"] = "Größe",
["CombulockButton"] = "CombustionHelper sperren",
["CombucritButton"] = "Kritische Masse Verfolgung",
["ComburefreshButton"] = "Zu frühe/verfehlte LB Warnung",
["CombureportButton"] = "Schadensbericht-Modus",
["Combureportthreshold"] = "Schwellwert :",
["CombuIgnitePredictButton"] = "Entzünden-Vorhersage",
["CombuIgniteAdjustbutton"] = "Entzünden-Timings :", 
["CombuffbButton"] = "FrostFeuerBlitz-Modus",
["CombuTimerbutton"] = "Timer rote Zone :",
["ComburefreshpyroButton"] = "Pyroschlag/Kampfeshitze Bericht",
["CombuimpactButton"] = "Aktiviere Einschlag Modus",
["CombutrackerButton"] = "Aktiviere Einäschern-Verfolgung",
["CombuchatButton"] = "Konfigurations-Nachrichten im Chat",
["CombuLBtrackerButton"] = "Aktiviere LB-Verfolgung",
["CombuLBtargetButton"] = "Zeige immer LB auf dem Ziel",
["LBtrackerPosition"] = "LB/FS-Verfolgung Position :",
["CombuAutohideInfo"] = "Auto-Verstecken Modus :",
["CombuBarButton"] = "Aktiviere Timer-Balken",
["CombuBarSlider"] = "Balkenbreite",
["CombuTextureInfo"] = "Balken Textur :",
["CombuFontInfo"] = "Schriftart :",
["CombuBorderInfo"] = "Rahmengrenze :",
["CombuBackgroundInfo"] = "Hintergrund :",
["CombuEdgeSizeSlider"] = "Kantengröße",
["CombuSliderInfo"] = "Unten kannst du die Zeit für das Ein- und Ausblenden und das Auto-Verstecken im Kampf anpassen.",
["CombubeforefadeSlider"] = "Timer pre fade",
["CombufadeoutspeedSlider"] = "Ausblenden",
["CombufadedtimeText"] = "Faded time",
["CombufadeinspeedSlider"] = "Einblenden",
["CombuafterfadeSlider"] = "Zeit nach Blenden",
["ComburesetButton"] = "SavedVariables zurücksetzen",
["CombuFlamestrikeButton"] = "Aktiviere Flammenstoß-Verfolgung",
["CombuTileSizeSlider"] = "Kachelgröße",
["CombuTileButton"] = "Kachelhintergrund",
["CombuInsetsSlider"] = "Bg Insets",
["Combubarcolornormal"] = "Balkenfarbe (normal)",
["Combubarcolorwarning"] = "Balkenfarbe (Warnung)",
["Combubgcolornormal"] = "Hintergrundfarbe (normal)",
["Combubgcolorimpact"] = "Hintergrundfarbe (Aufwarmen)",
["Combubgcolorcombustion"] = "Hintergrundfarbe (Einäschern OK)",
["CombuMunchingButton"] = "Entzünden munching Bericht",
["CombuLanguageInfo"] = "Sprache :",
["CombuSoundInfo"] = "Alarmschwelle :",
["CombuThresholdSoundButton"] = "Alarm für Schwellwert",
["Combuedgecolornormal"] = "Kantenfarbe (normal)",
["CombuTickPredictButton"] = "Combustion Tick damage/nbr prediction",
["CombuPyromaniacButton"] = "Alarm für Pyromane",
["Combubgcolorwarning"] = "Hintergrundfarbe (Alarm)",
["CombuHotStreakButton"] = "Alarm für Aufwarmen",
["CombuPyroEnableButton"] = "Aktivieren Pyroblast tracking",
["CombuLBEnableButton"] = "Aktivieren Bomb tracking",
}

-------------------------------
-- table for Living bomb tracker position dropdown
CombuLBpositionDE = {
"Oben",
"Unten",
"Rechte Seite",
"Linke Seite",
"Frei"
}

-------------------------------
-- table for Autohide dropdown
CombuAutohideListDE = {
"Kein Auto-Verstecken",
"Auto-Verstecken nur ausserhalb Kampf",
"Auto-Verstecken OOC und Einäschern ohne Abklingzeit",
}

-------------------------------
-- table for text within frame, try to stick to the lenght as it could overflow if bigger
CombuLabelDE = {["autohide"] = "Automatisch verstecken.",
["ignwhite0"] = "|cffffffff*%.0f Dmg|r",
["dmggreen0"] = "|cff00ff00%.0f Dmg|r",
["dmgred0"] = "|cffff0000%.0f Dmg|r",
["dmgwhite0"] = "|cffffffff%.0f Dmg|r",
["ignite"] = "|cffffffffEntzünden|r",
["ignshort"] = "|cffff0000Ent|r",
["flamestrike"] = "Flammenstoß",
["pyroblast"] = "Pyroschlag",
["blastwave"] = "Druckwelle FS",
["lbshort"] = "|cffff0000LB|r",
["ffbglyph"] = "|cffff0000Glyphe|r",
["ffbshort"] = "|cffff0000FFB|r",
["frostfire"] = "FrostFeuerB.",
["lb"] = "Lebende B.",
["pyroshort"] = "|cffff0000Pyro|r",
["ignCBgreen"] = "|cff00ff00Entzünden %.0f - CB ok|r",
["ignCBred"] = "|cffffcc00Entzünden %.0f - CB ok|r",
["combup"] = "Einäschern OK !",
["impactup"] = "|cff00ff00Einschlag für %.1f !!|r",
["combmin"] = "Einäschern in %d:%0.2d",
["combsec"] = "Einäschern in %.0fsec",
["critmasswhite"] = "|cffffffff Kritische Masse|r",
["critmassred"] = "|cffff0000Kritische Masse !!|r",
}

--end