-- translation notice : don't change the keys of tables or it won't work anymore (the text within the [ ]), the color coding part mustn't be changed either (|cff00ffff and |r).

-------------------------------
-- table for chat report settings, no problem changing the text lenght as it's outputted to chat frame
CombuLocTW = {["lockon"] = "|cff00ffff已鎖定「燃火助手」|r",
			["lockoff"] = "|cff00ffff已解鎖「燃火助手」|r",
			["reporton"] = "|cff00ffff已啟用「燃火助手」狀態報告|r",
			["ffbon"] = "|cff00ffff已啟用霜火箭模式|r",
			["ffboff"] = "|cff00ffff已停用霜火箭模式|r",
			["dmgreporton"] = "|cff00ffff已啟用傷害回報模式|r",
			["dmgreportoff"] = "|cff00ffff已停用傷害回報模式|r",
			["doton"] = "|cff00ffff已啟用燃火週期傷害監控|r",
			["dotoff"] = "|cff00ffff已停用燃火週期傷害監控|r",	
			["lbon"] = "|cff00ffff已啟用活體爆彈過早施放警告|r",
			["lboff"] = "|cff00ffff已停用活體爆彈過早施放警告|r",
			["pyroon"] = "|cff00ffff已啟用炎爆術回報模式|r",
			["pyrooff"] = "|cff00ffff已停用炎爆術回報模式|r",
			["impacton"] = "|cff00ffff已啟用衝擊模式|r",
			["impactoff"] = "|cff00ffff已停用衝擊模式|r",
			["baron"] = "|cff00ffff已啟用計時條模式|r",
			["baroff"] = "|cff00ffff已停用計時條模式|r",
			["criton"] = "|cff00ffff已啟用火焰重擊監控|r",
			["critoff"] = "|cff00ffff已停用火焰重擊監控|r",
			["ignpredon"] = "|cff00ffff已啟用點燃傷害預測 (BETA)|r",
			["ignpredoff"] = "|cff00ffff已停用點燃傷害預測 (BETA)|r",
			["fson"] = "|cff00ffff已啟用烈焰風暴監控|r",
			["fsoff"] = "|cff00ffff已停用烈焰風暴監控|r",
			["munchon"] = "|cff00ffff已啟用點燃吞噬回報|r",
			["munchoff"] = "|cff00ffff已停用點燃吞噬回報|r",
			["lbtrackon"] = "|cff00ffff已啟用活體爆彈監控|r",
			["lbtrackoff"] = "|cff00ffff已停用活體爆彈監控|r",
			["reset"] = "|cff00ffff已重設變數，可以登出遊戲囉！|r",
			["ffbglyphon"] = "|cff00ffff正在使用霜火箭雕文，已啟用霜火箭模式|r",
			["ffbglyphoff"] = "|cff00ffff未使用霜火箭雕文，已停用霜火箭模式|r",
			["autohidemess"] = "|cff00ffff「燃火助手」將於 %d 秒後載入|r",
			["startup"] = "|cff00ffff已載入「燃火助手」，請至「介面」->「插件」進行設定。|r",
			["combuon"] = "|cff00ffff未使用火焰天賦，已隱藏「燃火助手」介面。|r",
			["combuoff"] = "|cff00ffff正在使用火焰天賦，已載入「燃火助手」介面。|r",
			["lbrefresh"] = "|cffff0000 -- 太早施放活體爆彈於|cffffffff%s|cffff0000。--|r",
			["lbmiss"] = "|cffff00ff -- 施放於|cffffffff%s|cffff00ff的活體爆彈未命中！--",
			["pyrorefresh"] = "|cffff0000 -- 重新觸發焦炎之痕，浪費免錢炎爆術的孩子會被雷公劈。--|r",
            ["ignrep"] = "|cffff0000 -- 點燃傷害預測值 : |cffffffff%d |cffff0000- 點燃傷害實際值 : |cffffffff%d |cffff0000- 點燃傷害損失值 : |cffffffff%s |cffff0000--|r",
			["lbreport"] = "|cffff0000 -- 活體爆彈過早施放次數：|cffffffff%d |cffff0000--|r",
			["pyroreport"] = "|cffff0000 -- 热门数刷新为这场斗争： |cffffffff%d |cffff0000--|r",
			["slashcomm"] = "|cff00ffff正在開啟「燃火助手」設定視窗|r",
			["comburepthres"] = "|cff00ffff回報閥值已設為：%.0f 週期性傷害。|r",
			["ignadjvalue"] = "|cff00ffff>點燃預測微調監控時間已設為：%.1f 秒。|r",
			["redzonetimer"] = "|cff00ffff計時倒數警告閥值已設為：%.1f 秒。|r",
			["interfaceGraph"] = "Graphical Options",
			["combureport1"] = "|cffff0000 -- Total Combustion : |cffffffff%d |cffff0000- Ticks : |cffffffff%d |cffff0000- Dmg : |cffffffff%d |cffff0000- Targets : |cffffffff%d |cffff0000--|r",
			["combureport2"] = "|cffff0000 -- Prev. Combustion : |cffffffff%d |cffff0000- Ticks : |cffffffff%d |cffff0000- Dmg : |cffffffff%d |cffff0000- Targets : |cffffffff%d |cffff0000--|r",
			["pyroenableon"] = "|cff00ffffPyroblast tracker enabled|r",
			["pyroenableoff"] = "|cff00ffffPyroblast tracker disabled|r",
			["lbenableon"] = "|cff00ffffBomb tracker enabled|r",
			["lbenableoff"] = "|cff00ffffBomb tracker disabled|r",
            }
			
-------------------------------
-- table for option mouseover info, no problem changing text lenght here too, tooltip size change according to lenght
combuoptioninfotableTW = {
	["CombuScaleSlider"] = "請使用此滑動軸調整「燃火助手」的框架大小。注意：調整後，需重新將框架放置到目前位置。",
	["CombulockButton"] = "勾選以鎖定框架，取消勾選即可解鎖框架。",
	["CombucritButton"] = "啟用此功能，監控火法與術士是否已對我的當前目標施放提高法術爆擊機率的減益光環。",
	["ComburefreshButton"] = "啟用警告提示，太早施放活體爆彈，或者活體爆彈未命中時，在對話視窗中顯示警告 (另外附贈警告音效)。",
	["CombureportButton"] = "針對監控的每種法術，提供週期傷害詳細報告。第一跳週期傷害出現後，才可取得傷害資訊，因此數值報告會稍有延遲。",
	["Combureportthreshold"] = "啟用此功能，並在編輯欄位中設定數值，僅在當前目標身上觸發的點燃傷害高於此設定傷害值時，才改變燃火與衝擊的背景顏色配置。",
	["Combureportvalue"] = "啟用此功能，並在編輯欄位中設定數值，僅在當前目標身上觸發的點燃傷害高於此設定傷害值時，才改變燃火與衝擊的背景顏色配置。",
	["CombuIgnitePredictButton"] = "啟用點燃傷害預測回報 (BETA) 功能，無須待其每跳週期傷害出現，而可立即取得傷害預測資訊。透過此模式新增的傷害數值前方會有 * 號，代表該傷害數值可能與實際傷害數值有所出入。若該傷害預測值正確無誤，待每跳週期傷害出現後，傷害數值會變成綠字，若不正確，將呈現為紅字。",
	["CombuIgniteAdjustbutton"] = "點燃傷害預測 (BETA) 功能會在此設定時間區段內監控點燃的爆擊率，以便推估可能的傷害值。延遲 (lag) 情形可能會影響推算結果的正確性。若要進行測試，請先對訓練假人施以灼燒連發，若傷害數值多為紅字 (錯誤)，請調整此設定值，逐漸向上增加 0.1 秒，直到數值多為綠字 (正確) 為止。", 
	["CombuIgniteAdjustvalue"] = "點燃傷害預測 (BETA) 功能會在此設定時間區段內監控點燃的爆擊率，以便推估可能的傷害值。延遲 (lag) 情形可能會影響推算結果的正確性。若要進行測試，請先對訓練假人施以灼燒連發，若傷害數值多為紅字 (錯誤)，請調整此設定值，逐漸向上增加 0.1 秒，直到數值多為綠字 (正確) 為止。",
	["CombuffbButton"] = "啟用/停用霜火箭週期性傷害監控 (無論是否使用霜火箭雕文)。",
	["CombuTimerbutton"] = "輸入秒數，調整所有計時條的倒數警告秒數。",
	["CombuTimervalue"] = "輸入秒數，調整所有計時條的倒數警告秒數。",
	["ComburefreshpyroButton"] = "觸發焦炎之痕時若忘了施放免錢炎爆術，在對話視窗中顯示警告訊息，並在戰鬥結束後顯示報告。",
	["CombuimpactButton"] = "燃火冷卻完畢時，監控衝擊觸發情形，並變更背景顏色配置。",
	["CombutrackerButton"] = "在燃火框架中新增計時條，顯示當前目標燃火週期傷害的持續時間。 同时添加在聊天框的信息报告。",
	["CombuchatButton"] = "啟用/停用在對話框中顯示設定變更與自動隱藏的訊息。",
	["CombuLBtrackerButton"] = "啟用/停用多目標活體爆彈監控。啟用此功能時，將另外顯示框架，列出活體爆彈的所有施放資訊。",
	["CombuLBtargetButton"] = "使用多目標活體爆彈監控時，在監控框架中顯示/隱藏代表當前目標的綠色標記。",
	["LBtrackerPosition"] = "若要設定多目標活體爆彈監控框架的位置，請從下拉式選單中選擇希望將該框架設定於主框架的哪一側。",
	["LBtrackerDropDown"] = "若要設定多目標活體爆彈監控框架的位置，請從下拉式選單中選擇希望將該框架設定於主框架的哪一側",
	["CombuAutohideInfo"] = "請從下拉式選單中選擇自動隱藏模式。「不自動隱藏」：持續顯示「燃火助手」框架。「脫離戰鬥時自動隱藏」：僅在處於戰鬥狀態時顯示框架 (無論燃火是否已冷卻完畢)。「脫離戰鬥/燃火冷卻時自動隱藏」：僅在戰鬥中，且燃火已冷卻完畢時顯示框架。",
	["CombuAutohideDropDown"] = "請從下拉式選單中選擇自動隱藏模式。「不自動隱藏」：持續顯示「燃火助手」框架。「脫離戰鬥時自動隱藏」：僅在處於戰鬥狀態時顯示框架 (無論燃火是否已冷卻完畢)。「脫離戰鬥/燃火冷卻時自動隱藏」：僅在戰鬥中，且燃火已冷卻完畢時顯示框架。",
	["CombuBarButton"] = "啟用/停用活體爆彈、點燃、炎爆術週期傷害、霜火箭週期傷害的計時條。",
	["CombuBarSlider"] = "請使用此活動軸調整活體爆彈、點燃、炎爆術週期傷害、霜火箭週期傷害的計時條寬度。此設定將一併變更主框架寬度。",
	["Combubarcolornormal"] = "按一下色樣開啟色彩選擇器並選擇顏色，當倒數秒數高於警告秒數時，計時條將顯示為此色。",
	["Combubarcolorwarning"] = "按一下色樣開啟色彩選擇器並選擇顏色，當倒數秒數低於警告秒數時，計時條將顯示為此色。",
	["CombubeforefadeSlider"] = "請使用此滑動軸設定時間 (秒)，燃火冷卻時間經過此設定秒數之後，框架將自動隱藏。預設為 15 秒。",
	["CombufadeoutspeedSlider"] = "請使用此滑動軸，設定框架自動隱藏時，完全隱蔽所需的時間 (秒)。預設為 2 秒。",
	["CombufadedtimeText"] = "此值代表在燃火的冷卻時間中，框架將呈隱藏狀態的時間 (秒)。此設定涉及其他相關設定，因此你無法直接變更此設定值。",
	["CombufadedtimeFrame"] = "此值代表在燃火的冷卻時間中，框架將呈隱藏狀態的時間 (秒)。此設定涉及其他相關設定，因此你無法直接變更此設定值。",
	["CombufadeinspeedSlider"] = "請使用此滑動軸，設定框架自動顯示時，完全脫離隱藏狀態所需的時間 (秒)。預設為 2 秒。",
	["CombuafterfadeSlider"] = "請使用此滑動軸設定時間 (秒)，燃火冷卻時間剩餘此設定秒數時，框架將自動顯示。預設為 15 秒。",
	["ComburesetButton"] = "若不小心弄亂了設定，希望將設定還原至原始狀態，請按一下此按鈕。重新登入遊戲之後，即可復原所有設定。",
	["CombuFlamestrikeButton"] = "啟用/停用烈焰風暴監控，此功能會分別監控正常施放的烈焰風暴，以及透過衝擊波、火焰天賦所觸發的烈焰風暴 (強化烈焰風暴)，因為這兩者造成的週期傷害會相疊加。僅監控這兩者的最後一跳週期傷害，避免額外使用不必要的計時器。",
	["CombuMunchingButton"] = "啟用/停用點燃吞噬回報，記錄所有爆擊的火焰法術與產生的點燃傷害。戰鬥結束時會向你回報這些數據，供你瞭解你因為點燃吞噬、目標太早陣亡而損失多少傷害輸出。這些數據雖並非至關重要，卻能讓你瞭解原應有的傷害輸出量。☆注意☆：由於衝擊會造成週期傷害傳染，因此僅會計算你對當前目標所造成的爆擊傷害！另外，此功能也需配合點燃傷害預測機制，記得啟動點燃傷害預測 (BETA) 功能，才可正常使用本功能。",
	["Combubgcolorcombustion"] = "燃火冷卻完畢、三大週期性傷害將結束時，或當你啟用警告時間閥值，且已超過該閥值時，框架將呈現的背景色與框線色。",
	["Combubgcolorimpact"] = "觸發衝擊效果時，框架將呈現的背景色與框線色。",
	["Combubgcolornormal"] = "燃火正在冷卻，且未觸發衝擊效果時，框架將呈現的背景色。若選擇其他背景，預設顏色可能會太暗。",
	["CombuTextureDropDown"] = "請從下拉式選單中選擇計時條的材質。",
	["CombuTextureInfo"] = "請從下拉式選單中選擇計時條的材質。",
	["CombuFontDropDown"] = "請從下拉式選單中選擇所有字體的字型。",
	["CombuFontInfo"] = "請從下拉式選單中選擇所有字體的字型。",
	["CombuBorderDropDown"] = "請從下拉式選單中選擇主框架、活體爆彈/烈焰風暴監控框架的框線。",
	["CombuBorderInfo"] = "請從下拉式選單中選擇主框架、活體爆彈/烈焰風暴監控框架的框線。",
	["CombuBackgroundDropDown"] = "請從下拉式選單中選擇主框架、活體爆彈/烈焰風暴監控框架的背景。",
	["CombuBackgroundInfo"] = "請從下拉式選單中選擇主框架、活體爆彈/烈焰風暴監控框架的背景",
	["CombuEdgeSizeSlider"] = "請使用滑動軸設定主框架、活體爆彈/烈焰風暴監控框架的框線粗細。",
	["CombuTileSizeSlider"] = "請使用滑動軸設定主框架、活體爆彈/烈焰風暴監控框架背景材質圖樣的大小。(勾選「圖樣」時才可使用此滑動軸。)",
	["CombuTileButton"] = "啟用/停用主框架、活體爆彈/烈焰風暴監控框架的背景圖樣。啟用時，選定的背景圖樣將依設定大小並排顯示於框架中。",
	["CombuInsetsSlider"] = "請使用此滑動軸設定框線與背景圖樣間的間距。",
	["CombuSoundInfo"] = "請從下拉式選單中選擇倒數計時完畢時的警告音效。",
	["CombuSoundDropDown"] = "請從下拉式選單中選擇倒數計時完畢時的警告音效。",
    ["CombuThresholdSoundButton"] = "啟用警告音效，超過點燃傷害閥值時給予警示。",
    ["CombuTickPredictButton"] = "Replace the Ignite damage value in the Status zone by the estimated damage for each tick of Combustion and the number of ticks depending from your current haste.",
	["CombuPyroEnableButton"] = "Enable or disable Pyroblast tracking in the main window.",
	["CombuLBEnableButton"] = "Enable or disable Bomb tracking in the main window.",
	}

-------------------------------
-- table for option panel localisation, try to stick to the lenght as it could overflow if bigger
CombuOptLocTW = {
	["CombuScaleSlider"] = "大小",
	["CombulockButton"] = "鎖定",
	["CombucritButton"] = "火焰重擊監控",
	["ComburefreshButton"] = "活體爆彈施放失誤警告",
	["CombureportButton"] = "傷害回報模式",
	["Combureportthreshold"] = "點燃閥值:",
	["CombuIgnitePredictButton"] = "點燃傷害預測 (BETA)",
	["CombuIgniteAdjustbutton"] = "點燃預測監控微調:", 
	["CombuffbButton"] = "啟用霜火箭模式",
	["CombuTimerbutton"] = "倒數警告秒數:",
	["ComburefreshpyroButton"] = "炎爆術/焦炎之痕回報",
	["CombuimpactButton"] = "啟用衝擊模式",
	["CombutrackerButton"] = "啟用燃火監控",
	["CombuchatButton"] = "顯示設定訊息",
	["CombuLBtrackerButton"] = "啟用活體爆彈監控",
	["CombuLBtargetButton"] = "永遠顯示活體爆彈目標",
	["LBtrackerPosition"] = "監控框架位置:",
	["CombuAutohideInfo"] = "自動隱藏模式:",
	["CombuBarButton"] = "啟用計時條模式",
	["CombuBarSlider"] = "寬度",
	["CombuTextureInfo"] = "材質:",
	["CombuFontInfo"] = "字型:",
	["CombuBorderInfo"] = "框架框線:",
	["CombuBackgroundInfo"] = "背景:",
	["CombuEdgeSizeSlider"] = "框線粗細",
	["CombuSliderInfo"] = "請於下方調整計時條淡入、淡出與戰鬥中自動隱藏的相關設定。",
	["CombubeforefadeSlider"] = "淡出時機",
	["CombufadeoutspeedSlider"] = "淡出",
	["CombufadedtimeText"] = "淡出時間",
	["CombufadeinspeedSlider"] = "淡入",
	["CombuafterfadeSlider"] = "淡入時機",
	["ComburesetButton"] = "重設變數",
	["CombuFlamestrikeButton"] = "啟用烈焰風暴監控",
	["CombuTileSizeSlider"] = "圖樣大小",
	["CombuTileButton"] = "材質背景",
	["CombuInsetsSlider"] = "間距",
	["Combubarcolornormal"] = "計時條色(正常)",
	["Combubarcolorwarning"] = "計時條色(警告)",
	["Combubgcolornormal"] = "背景色(正常)",
	["Combubgcolorimpact"] = "背景色(热)",
	["Combubgcolorcombustion"] = "背景色(燃火)",
	["CombuMunchingButton"] = "點燃吞噬回報",
	["CombuLanguageInfo"] = "語言:",
    ["CombuSoundInfo"] = "警告音效:",
    ["CombuThresholdSoundButton"] = "啟用警告音效",
    ["CombuTickPredictButton"] = "Combustion Tick damage/nbr prediction",
    ["CombuPyromaniacButton"] = "Missing Pyromaniac warning",
	["Combubgcolorwarning"] = "背景色(警告)",
    ["CombuHotStreakButton"] = "热",
	["CombuPyroEnableButton"] = "Enable Pyroblast tracking",
	["CombuLBEnableButton"] = "Enable Bomb tracking",

	}

-------------------------------
-- table for Living bomb tracker position dropdown
CombuLBpositionTW = {
   "上方",
   "下方",
   "右方",
   "左方",
   "免费"
	}

-------------------------------
-- table for Autohide dropdown
CombuAutohideListTW = {
   "不自動隱藏",
   "脫離戰鬥時自動隱藏",
   "脫離戰鬥/燃火冷卻時自動隱藏",
}

-------------------------------
-- table for text within frame, try to stick to the lenght as it could overflow if bigger
CombuLabelTW = {["autohide"] = "自動隱藏…",
				["ignwhite0"] = "|cffffffff*%.0f Dmg|r",
				["dmggreen0"] = "|cff00ff00%.0f Dmg|r",
				["dmgred0"] = "|cffff0000%.0f Dmg|r",
				["dmgwhite0"] = "|cffffffff%.0f Dmg|r",
				["ignite"] = "|cffffffff點燃|r",
				["ignshort"] = "|cffff0000無|r",
				["flamestrike"] = "烈焰風暴",
				["blastwave"] = "強化烈焰風暴",
				["lbshort"] = "|cffff0000無|r",
				["ffbglyph"] = "|cffff0000雕文|r",
				["ffbshort"] = "|cffff0000無|r",
				["frostfire"] = "霜火箭",
				["pyroblast"] = "炎爆術",
				["lb"] = "活體爆彈",
				["pyroshort"] = "|cffff0000無|r",
				["ignCBgreen"] = "|cff00ff00點燃：%.0f - 燃火希望|r",
				["ignCBred"] = "|cffffcc00點燃：%.0f - 燃火希望|r",
				["combup"] = "燃火冷卻完畢！",
				["impactup"] = "|cff00ff00衝擊倒數 %.1f！|r",
				["combmin"] = "燃火冷卻 %d:%0.2d",
				["combsec"] = "燃火冷卻 %.0fsec",
				["critmasswhite"] = "|cffffffff 火焰重擊|r",
				["critmassred"] = "|cffff0000無火焰重擊！|r",
				}